---
name: Feature Request
description: Suggest a new feature for the Credit Scoring Engine
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature
      placeholder: e.g., Add support for multiple scoring models
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Currently, the system only supports one scoring model, but users need to compare multiple models...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: Add a model selection interface that allows users to create and manage multiple scoring models...
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: How would this feature be used?
      placeholder: |
        - As a loan officer, I want to compare different scoring models
        - As an administrator, I want to configure multiple models for different loan types
        - As a developer, I want to extend the scoring system with custom algorithms
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocker for my use case
        - High - Very important for my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor changes needed
        - Medium - Moderate development effort
        - Complex - Significant development required
        - Major - Architectural changes needed
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives or workarounds?
      placeholder: I've tried using external scoring services, but they don't integrate well...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        - Mockups or wireframes
        - Similar implementations in other systems
        - Technical considerations

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can provide documentation
        - label: I cannot contribute at this time

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/Mufwaya2025/Credit-Scoring-Engine-v01/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the requested feature
          required: true